services:
 
  agency.generate_prompt_use_case:
    class: application.agency.GeneratePromptUseCase
    arguments:
      - '@pyperclip'
      - '@obsidian.vault'
      - '%PROMPT_TEMPLATE_PATH%'

  agency.prompt_agent_use_case:
    class: application.agency.PromptAgentUseCase
    arguments: ['@agency.agent_registry']

  agency.run_discord_bot_use_case:
    class: application.agency.RunDiscordBotUseCase
    arguments: ['@agency.prompt_agent_use_case']

  agency.index_documents_use_case:
    class: application.agency.IndexDocumentsUseCase
    arguments: ['@faiss.indexer']
  
  agency.agent_registry:
    class: domain.registry.Registry
    arguments: 
      services: !tagged_iterator { tag: agent, index_by: alias }

  agency.agent_factory:
    class: infrastructure.agency.AgentFactory
    arguments: ['@agency.tool_factory']

  agency.tool_factory:
    class: infrastructure.agency.ToolFactory
  
  agency.agent.pr:
    class: infrastructure.agency.PRAgent
    arguments: 
      prompt_generator: '@obsidian.prompt_generator'
      include_rule: '*.py|*.ts|*.js|*.json|*.yml|*.yaml|*.md|*.tsx|*.jsx|*.css|*.scss|*.svg|*.sequelizerc'
      exclude_rule: '.git|venv|__pycache__|dist|build|.env*|node_modules|.turbo|pnpm-lock.yaml|package-lock.json'
      exclude_gitignore: true
    tags:
      - { name: agent, alias: pr }

  agency.agent.scheduling:
    class: infrastructure.agency.SchedulingAgent
    tags:
      - { name: agent, alias: scheduling }

  agency.agent.search:
    class: infrastructure.agency.SearchAgent
    arguments: ['@faiss.search_engine','langchain.document_mapper','@openai.client','o1']
    tags:
      - { name: agent, alias: search }

  daily_voice_notes.assimilate_voice_note_use_case:
    class: application.daily_voice_notes.AssimilateVoiceNoteUseCase
    arguments: 
      - '@transcription.transcriber'
      - '@daily_voice_notes.document_consolidator'
      - '%TRANSCRIPTS_BASE_PATH%'

  daily_voice_notes.document_consolidator:
    class: infrastructure.daily_voice_notes.DailyNoteConsolidator
    arguments: ['@openai.client','@obsidian.vault']

  faiss.indexer:
    class: infrastructure.faiss.FAISSIndexer
    arguments:
      document_loader: '@langchain.obsidian_document_loader'
      mapper: '@langchain.document_mapper'
      docs_path: '%OBSIDIAN_VAULT_PATH%'
      chunk_size: 1000
      chunk_overlap: 100
      save_path: '%FAISS_INDEX_PATH%'

  faiss.search_engine:
    class: infrastructure.faiss.FAISSSearchEngine
    arguments: ['%FAISS_INDEX_PATH%', 1]

  langchain.document_mapper:
    class: infrastructure.langchain.LangchainDocumentMapper

  langchain.obsidian_document_loader:
    class: infrastructure.langchain.ObsidianDocumentLoader
    arguments: ['@langchain.document_mapper','%OBSIDIAN_VAULT_PATH%']

  openai.client:
    class: infrastructure.openai.OpenAIClient
    arguments: ['%OPENAI_API_KEY%']

  obsidian.prompt_generator:
    class: infrastructure.obsidian.ObsidianPromptGenerator
    arguments: ['@obsidian.vault', '%PROMPT_TEMPLATE_PATH%']

  obsidian.vault:
    class: infrastructure.obsidian.ObsidianVault
    arguments: ['%OBSIDIAN_VAULT_PATH%']

  pyperclip:
    class: infrastructure.pyperclip.Pyperclip

  traceback.build_troubleshooting_prompt_use_case:
    class: application.traceback.BuildTroubleshootingPromptUseCase
    arguments: ['@traceback.prompt_builder']

  traceback.prompt_builder:
    class: infrastructure.traceback.TracebackPromptBuilder
    arguments: ['@pyperclip']

  transcription.transcribe_audio_use_case:
    class: application.transcription.TranscribeAudioUseCase
    arguments: ['@transcription.transcriber']

  transcription.transcriber:
    class: infrastructure.amazon.AmazonTranscribe
    arguments: ['%TRANSCRIPTS_BUCKET%', '%AWS_PATH%']